dist: xenial
sudo: true

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libboost-dev libeigen3-dev

script:
  - mkdir -p build
  - cd build
  - cmake -DTEST=ON ..
  - make
  - make test
