#ifndef COBRAMODELPARSER_DATAELEMENTTAG_HPP
#define COBRAMODELPARSER_DATAELEMENTTAG_HPP

namespace CobraModelParser {
    class DataElementTag {

    };
}

#endif //COBRAMODELPARSER_DATAELEMENTTAG_HPP
